---
# k8s/configmap-template.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: notification-service
  labels:
    app: notification-service
data:
  # Database Configuration
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_SCHEMA: "${POSTGRES_SCHEMA}"

  # Notification Service Database User
  NOTIFICATION_SERVICE_DB_USER: "${NOTIFICATION_SERVICE_DB_USER}"

  # Redis Configuration
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PORT: "${REDIS_PORT}"
  REDIS_DB: "${REDIS_DB}"

  # Rate Limiting Configuration
  RATE_LIMIT_REQUESTS: "${RATE_LIMIT_REQUESTS}"
  RATE_LIMIT_WINDOW: "${RATE_LIMIT_WINDOW}"

  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"

  # Logging Configuration
  LOG_LEVEL: "${LOG_LEVEL}"
  LOG_FILE_PATH: "${LOG_FILE_PATH}"
  SERVICE_NAME: "${SERVICE_NAME}"
  ENVIRONMENT: "${ENVIRONMENT}"

  # OAuth2 Service Configuration
  OAUTH2_SERVICE_ENABLED: "${OAUTH2_SERVICE_ENABLED}"
  OAUTH2_SERVICE_TO_SERVICE_ENABLED: "${OAUTH2_SERVICE_TO_SERVICE_ENABLED}"
  OAUTH2_INTROSPECTION_ENABLED: "${OAUTH2_INTROSPECTION_ENABLED}"
  OAUTH2_CLIENT_ID: "${OAUTH2_CLIENT_ID}"
