---
# k8s/secret-template.yaml
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: notification-service
  labels:
    app: notification-service
type: Opaque
stringData:
  # Plain text secrets - Kubernetes will automatically base64 encode them
  # Values are substituted from environment variables

  # Notification Service Database Password
  NOTIFICATION_SERVICE_DB_PASSWORD: '${NOTIFICATION_SERVICE_DB_PASSWORD}'
