name: Security Vulnerability (Low Severity)
description: Report a low-severity security issue
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees:
  - jsamuelsen11

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT: For Critical/High Severity Issues

        **If this is a critical or high severity security vulnerability, please DO NOT file a public issue.**

        Instead, use [GitHub Security Advisories](https://github.com/Recipe-Web-App/notification-service/security/advisories/new) to privately report the vulnerability.

        This template is ONLY for low-severity security issues that don't pose an immediate risk.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low - Minimal impact, difficult to exploit
        - Informational - Security best practice recommendation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security vulnerability or concern
      placeholder: Clear description of the security issue...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Information Disclosure
        - Authentication/Authorization
        - Input Validation
        - Configuration Issue
        - Dependency Vulnerability
        - Code Quality/Best Practice
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact of this vulnerability?
      placeholder: Describe the potential impact...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be demonstrated?
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - API
        - Authentication
        - Database
        - Configuration
        - Dependencies
        - Other
    validations:
      required: true

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Responsible Disclosure
      description: Please confirm
      options:
        - label: I confirm this is a LOW severity issue and does not pose an immediate security risk
          required: true
        - label: I understand that critical/high severity issues should use GitHub Security Advisories
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about this security issue
      placeholder: Mitigation suggestions, related vulnerabilities, references...
